### PR TITLE
Implemented save code feature

### PR DESCRIPTION
**Pull request by JSSaini07**
modified runCode() to save the code result in mongoDB and generate link for the code.
Implemented savedCodeView() to show the code according to code_id

### CODE REVIEW

**Comment by sahildua2305** [comment]
Pretty neat work! Thanks @JSSaini07 

However can we instead use PostgreSQL? The reason for preferring PostgreSQL is that Heroku supports that only. It doesn't support MongoDB for free tier accounts.

Will it be a big issue to port this to PostgreSQL database? Let me know what do you think. I can help you on the way as well.

**Comment by JSSaini07** [comment]
Hello, I dont think there is any problem using MongoDB with heroku on a
free tier account, i am using it currently on 2 of my apps, one of them is
a compiler <http://compileride.herokuapp.com/>.

Thank you!

**Comment by sahildua2305** [comment]
Oh really? I will check once again. Last time I checked, they didn't allow MongoDB on free tier account. When did you host your app with them?

**Comment by sahildua2305** [comment]
@JSSaini07 Is the logic for `code_id` generation same as that for your compiler IDE?

If so, I am highly doubtful about having a new `code_id` everytime the code is run/compiled. Ideally, there should be one `code_id` that will remain constant for that particular piece of code. It's contents can be changed, hence its run/compile status will change.

Please clarify this.

**Comment by sahildua2305** [comment]
For example, please see HackerEarth's [IDE](https://code.hackerearth.com/).

**Comment by JSSaini07** [comment]
I have given them my credit card info, they don't charge for the free plan.
Linking it directly with mlabs could work.I am trying to deploy this app
using another account with no credit card info, will let you know about the
outcome.

**Comment by JSSaini07** [comment]
no the logic is not the same, in my app i used the self generated mongo
id(which is generated on insertion in db). In this app i am using the
hackerearth's code_id that is present in the response. so, it will be
unique for each code.

**Comment by JSSaini07** [comment]
i viewed my compiler's logic again, i have used the hackerearth's code_id
and not the mongo self generating _id. So , yes the logic for both is same.

**Comment by mananpal1997** [comment]
There can be same codes from different users. This would acquire space.
Can't we have code as a key and list of usernames of people corresponding to that code?

**Comment by JSSaini07** [comment]
@sahildua2305  There is no need of credit card information, just create a free account at mlabs.com and use it in your app. Here is the live version of your app with a connected mongoDB [testHackIDE](http://hackidetest.herokuapp.com)

**Comment by sahildua2305** [comment]
@JSSaini07 This looks great!

Some feedback, can we by default enable (check the tickbox) input if the result contains some input? To make sure we provide consistent experience for users?

**Comment by mananpal1997** [comment]
@sahildua2305 what does this mean : "enable input if result contains some input"?

**Comment by sahildua2305** [comment]
@mananpal1997 If you open [this link](hackidetest.herokuapp.com/code_id=7cdbfep/), you can see the `Use custom input to test the code` checkbox is unticked. But since there was some custom input when this code (and its run status) was saved, we should by default show the input box.

Agree?

**Comment by JSSaini07** [comment]
@sahildua2305 i am caught up in the placement process, will do it as soon
as i get time :)

**Comment by sahildua2305** [comment]
@JSSaini07 Don't worry. I will take this ahead by making the required change. Good luck!

**Comment by sahildua2305** [comment]
@JSSaini07 thanks a lot for working on this. I have made some refactoring of code along with some minor changes. Do have a look at them to get feedback about your code. Very good job. Expecting more contributions from you in future. :smile:

**Comment by JSSaini07** [comment]
Sure :D

**Pull request merged**
